/*
 * Copyright (C) 2024 Syntarou YOSHIDA
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jp.synthtarou.mixtone.synth.view;

import java.io.File;
import javax.swing.JFileChooser;
import jp.synthtarou.mixtone.synth.view.listmodel.ModelForINSTEntry;
import jp.synthtarou.mixtone.synth.view.listmodel.ModelForINSTEntryList;
import jp.synthtarou.mixtone.synth.view.listmodel.ModelForSHDRList;
import jp.synthtarou.mixtone.synth.view.listmodel.ModelForPHDREntryList;
import jp.synthtarou.mixtone.synth.view.listmodel.TheConsole;
import jp.synthtarou.mixtone.synth.XTSynthesizer;
import jp.synthtarou.mixtone.synth.oscilator.XTOscilator;
import jp.synthtarou.mixtone.synth.soundfont.wrapper.IBAGEntry;
import jp.synthtarou.mixtone.synth.soundfont.wrapper.IGENEntry;
import jp.synthtarou.mixtone.synth.soundfont.wrapper.INSTEntry;
import jp.synthtarou.mixtone.synth.soundfont.wrapper.INSTEntryList;
import jp.synthtarou.mixtone.synth.soundfont.wrapper.PBAGEntry;
import jp.synthtarou.mixtone.synth.soundfont.wrapper.PHDREntry;
import jp.synthtarou.mixtone.synth.soundfont.wrapper.PHDREntryList;
import jp.synthtarou.mixtone.synth.view.listmodel.ModelForPHDREntry;

/**
 *
 * @author Syntarou YOSHIDA
 */
public class XTSoundFontView extends javax.swing.JPanel {

    /**
     * Creates new form XTMixerView
     */
    public XTSoundFontView(XTSynthesizer synth) {
        initComponents();
        _synth = synth;
        _synth.startAudioStream();
       jTextFieldFileName.setEditable(false);
    }
    
    XTSynthesizer _synth;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTextFieldFileName = new javax.swing.JTextField();
        jButtonBrowse = new javax.swing.JButton();
        jButtonClearSel = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList1ListPreset = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList2Preset = new javax.swing.JList<>();
        jSplitPane4 = new javax.swing.JSplitPane();
        jPanelInstrument = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList3ListInst = new javax.swing.JList<>();
        jPanelZone = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4Inst = new javax.swing.JList<>();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(jTextFieldFileName, gridBagConstraints);

        jButtonBrowse.setText("Browse");
        jButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseActionPerformed(evt);
            }
        });
        add(jButtonBrowse, new java.awt.GridBagConstraints());

        jButtonClearSel.setText("ClearSel");
        jButtonClearSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearSelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        add(jButtonClearSel, gridBagConstraints);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane3.setDividerLocation(300);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Preset"));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jList1ListPreset.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ListPresetValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(jList1ListPreset);

        jPanel1.add(jScrollPane5);

        jSplitPane3.setLeftComponent(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("PresetBag ListEntries"));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jList2Preset.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2PresetValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(jList2Preset);

        jPanel2.add(jScrollPane6);

        jSplitPane3.setRightComponent(jPanel2);

        jSplitPane1.setLeftComponent(jSplitPane3);

        jSplitPane4.setDividerLocation(300);

        jPanelInstrument.setBorder(javax.swing.BorderFactory.createTitledBorder("Instrument"));
        jPanelInstrument.setLayout(new javax.swing.BoxLayout(jPanelInstrument, javax.swing.BoxLayout.LINE_AXIS));

        jList3ListInst.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList3ListInstValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList3ListInst);

        jPanelInstrument.add(jScrollPane2);

        jSplitPane4.setLeftComponent(jPanelInstrument);

        jPanelZone.setBorder(javax.swing.BorderFactory.createTitledBorder("InstrumentBag ListEntry"));
        jPanelZone.setLayout(new java.awt.GridBagLayout());

        jList4Inst.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList4InstValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(jList4Inst);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelZone.add(jScrollPane4, gridBagConstraints);

        jButton60.setText("Play 60");
        jButton60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton60ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        jPanelZone.add(jButton60, gridBagConstraints);

        jButton61.setText("Play 61");
        jButton61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton61ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        jPanelZone.add(jButton61, gridBagConstraints);

        jButton62.setText("Play 62");
        jButton62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton62ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        jPanelZone.add(jButton62, gridBagConstraints);

        jButton63.setText("Play 63");
        jButton63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton63ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanelZone.add(jButton63, gridBagConstraints);

        jButton64.setText("Play 64");
        jButton64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton64ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        jPanelZone.add(jButton64, gridBagConstraints);

        jButton69.setText("Play 69");
        jButton69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton69ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        jPanelZone.add(jButton69, gridBagConstraints);

        jButton70.setText("Play 70");
        jButton70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton70ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        jPanelZone.add(jButton70, gridBagConstraints);

        jSplitPane4.setRightComponent(jPanelZone);

        jSplitPane1.setRightComponent(jSplitPane4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jSplitPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser("c:\\midi");
        chooser.showOpenDialog(this);
        File f = chooser.getSelectedFile();
        if (f != null) {
            jTextFieldFileName.setText("" + f);
            startOpen(f);
        }
    }//GEN-LAST:event_jButtonBrowseActionPerformed

    private void jList1ListPresetValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ListPresetValueChanged
        int index = jList1ListPreset.getSelectedIndex();
        if (index >= 0) {
            try {
                PHDREntry entry = _listModel1PHDRList.getPHDREntry(index);
                _listModel2PHDREntry = new ModelForPHDREntry(entry);
                System.err.println("listModel2 " + index + " / " +_listModel2PHDREntry.getSize());
                jList2Preset.setModel(_listModel2PHDREntry);
            }catch(Throwable ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jList1ListPresetValueChanged

    private void jList3ListInstValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList3ListInstValueChanged
        int index = jList3ListInst.getSelectedIndex();
        if (index >= 0) {
            try {
                INSTEntry entry = _listModel3InstList.getINSTEntry(index);
                _listModel4InstEntry = new ModelForINSTEntry(entry);
                System.err.println("listModel4 "  + index + " / " + _listModel4InstEntry.getSize());
                jList4Inst.setModel(_listModel4InstEntry);
            }catch(Throwable ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jList3ListInstValueChanged

    private void jButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton60ActionPerformed
        playOneShot(60);
    }//GEN-LAST:event_jButton60ActionPerformed

    private void jButton61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton61ActionPerformed
        playOneShot(61);
    }//GEN-LAST:event_jButton61ActionPerformed

    private void jButton62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton62ActionPerformed
        playOneShot(62);
    }//GEN-LAST:event_jButton62ActionPerformed

    private void jButton63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton63ActionPerformed
        playOneShot(63);
    }//GEN-LAST:event_jButton63ActionPerformed

    private void jButton64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton64ActionPerformed
        playOneShot(64);
    }//GEN-LAST:event_jButton64ActionPerformed

    private void jButton69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton69ActionPerformed
        playOneShot(69);
    }//GEN-LAST:event_jButton69ActionPerformed

    private void jButton70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton70ActionPerformed
        playOneShot(70);
    }//GEN-LAST:event_jButton70ActionPerformed

    private void jList2PresetValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2PresetValueChanged
        int index = jList2Preset.getSelectedIndex();
        if (index >= 0) {
            try {
                PBAGEntry entry = _listModel2PHDREntry.getPBAGEntry(index);
                INSTEntryList list = new INSTEntryList(_synth._sfz);
                _listModel3InstList = new ModelForINSTEntryList(list, entry);
                System.err.println("list3 = "+  _listModel3InstList.getSize());
                jList3ListInst.setModel(_listModel3InstList);
            }catch(Throwable ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jList2PresetValueChanged

    private void jList4InstValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList4InstValueChanged
        int index = jList4Inst.getSelectedIndex();
        if (index >= 0) {
            try {
                IBAGEntry entry = _listModel4InstEntry.getIBAGEntry(index);
                _selectedIBAGEntry = entry;
            }catch(Throwable ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jList4InstValueChanged

    private void jButtonClearSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearSelActionPerformed
        if (_synth != null && _synth._sfz != null) {
            PHDREntryList listPreset = new PHDREntryList(_synth._sfz);
            _listModel1PHDRList = new ModelForPHDREntryList(listPreset);
            System.err.println("listMode1 - / " + _listModel1PHDRList.getSize());
            jList1ListPreset.setModel(_listModel1PHDRList);

            INSTEntryList listInst = new INSTEntryList(_synth._sfz);
            _listModel3InstList = new ModelForINSTEntryList(listInst, null);
            System.err.println("listMode13 - / " + _listModel3InstList.getSize());
            jList3ListInst.setModel(_listModel3InstList);
        }
    }//GEN-LAST:event_jButtonClearSelActionPerformed

    TheConsole _console;            

    public void startOpen(File f) {
        try {
            _synth.openSoundfont(f);
            _synth.resetGM();
            PHDREntryList listPreset = new PHDREntryList(_synth._sfz);
            _listModel1PHDRList = new ModelForPHDREntryList(listPreset);
            System.err.println("listMode1 - / " + _listModel1PHDRList.getSize());
            jList1ListPreset.setModel(_listModel1PHDRList);

            INSTEntryList listInst = new INSTEntryList(_synth._sfz);
            _listModel3InstList = new ModelForINSTEntryList(listInst, null);
            System.err.println("listMode13 - / " + _listModel3InstList.getSize());
            jList3ListInst.setModel(_listModel3InstList);
        }catch(Throwable ex) {
            ex.printStackTrace();
        }
    }
    
    ModelForPHDREntryList _listModel1PHDRList;
    ModelForPHDREntry _listModel2PHDREntry;

    ModelForINSTEntryList _listModel3InstList;
    ModelForINSTEntry _listModel4InstEntry;

    ModelForSHDRList _listModelSHDRProperty;
    IBAGEntry _selectedIBAGEntry;
    
    public void playOneShot(int note) {
        if (_selectedIBAGEntry != null) {
            IGENEntry ent = null;
            XTOscilator osc = new XTOscilator(0, note, 0.8, _synth._sfz, 
                    ent.getSampleId(), 
                    ent.getSampleModes() != null, 
                    ent.getOverridingRootKey(), 
                    ent.getPan());
            _synth.startAudioStream().push(osc);
            new Thread(() -> {
                try {
                    Thread.sleep(1000);
                }catch(Throwable ex) {
                    ex.printStackTrace();
                }
                osc.noteOff();
            }).start();
        }    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButtonBrowse;
    private javax.swing.JButton jButtonClearSel;
    private javax.swing.JList<String> jList1ListPreset;
    private javax.swing.JList<String> jList2Preset;
    private javax.swing.JList<String> jList3ListInst;
    private javax.swing.JList<String> jList4Inst;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelInstrument;
    private javax.swing.JPanel jPanelZone;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JTextField jTextFieldFileName;
    // End of variables declaration//GEN-END:variables
}
