/*
 * Copyright (C) 2024 Syntarou YOSHIDA
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jp.synthtarou.mixtone.synth.view;

import javax.swing.JFrame;
import jp.synthtarou.mixtone.synth.view.listmodel.TheConsole;
import jp.synthtarou.mixtone.synth.XTSynthesizer;
import jp.synthtarou.mixtone.synth.XTSynthesizerSetting;

/**
 *
 * @author Syntarou YOSHIDA
 */
public class XTSynthesizerFrame extends javax.swing.JFrame {
    TheConsole _console;         
    XTSynthesizer _synth;

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame explorer = new jp.synthtarou.mixtone.synth.view.XTSynthesizerFrame();
                explorer.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                explorer.setVisible(true);
            }
        });
    }

    XTMixerView _mixerView;
    XTSoundFontView _soundFontView;

    /**
     * Creates new form SoundFontExplorerFrame
     */
    public XTSynthesizerFrame() {
        initComponents();
        _synth = XTSynthesizerSetting.getSetting().getSynthInstance();
        _mixerView = new XTMixerView(_synth);
        _soundFontView = new XTSoundFontView(_synth);
        jScrollPaneSoundFont.getViewport().add(_soundFontView);
        jScrollPaneMixer.getViewport().add(_mixerView);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneMixer = new javax.swing.JTabbedPane();
        jPanelMixer = new javax.swing.JPanel();
        jScrollPaneMixer = new javax.swing.JScrollPane();
        jPanelSoundFont = new javax.swing.JPanel();
        jScrollPaneSoundFont = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanelMixer.setLayout(new javax.swing.BoxLayout(jPanelMixer, javax.swing.BoxLayout.LINE_AXIS));
        jPanelMixer.add(jScrollPaneMixer);

        jTabbedPaneMixer.addTab("Mixer", jPanelMixer);

        jPanelSoundFont.setLayout(new javax.swing.BoxLayout(jPanelSoundFont, javax.swing.BoxLayout.LINE_AXIS));
        jPanelSoundFont.add(jScrollPaneSoundFont);

        jTabbedPaneMixer.addTab("SoundFont", jPanelSoundFont);

        getContentPane().add(jTabbedPaneMixer);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelMixer;
    private javax.swing.JPanel jPanelSoundFont;
    private javax.swing.JScrollPane jScrollPaneMixer;
    private javax.swing.JScrollPane jScrollPaneSoundFont;
    private javax.swing.JTabbedPane jTabbedPaneMixer;
    // End of variables declaration//GEN-END:variables
}
