/*
 * Copyright 2023 Syntarou YOSHIDA.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jp.synthtarou.midimixer.mx70console;

import java.awt.Dimension;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListDataEvent;
import javax.swing.event.ListDataListener;
import jp.synthtarou.midimixer.libs.common.MXWrapList;
import jp.synthtarou.midimixer.libs.console.ConsoleElement;
import jp.synthtarou.midimixer.libs.console.ConsoleModel;
import jp.synthtarou.midimixer.libs.midi.MXUtilMidi;
import jp.synthtarou.midimixer.libs.midi.driver.SysexSplitter;
import jp.synthtarou.midimixer.libs.swing.MXFileOpenChooser;

/**
 *
 * @author Syntarou YOSHIDA
 */
public class MX70SysexPanel extends javax.swing.JPanel {
    ConsoleModel _list;
    SysEXFile _file;
    MXWrapList<Integer> _listPort = MXUtilMidi.createPortAssigned(false);

    /**
     * Creates new form MX70SysexPanel
     */
    public MX70SysexPanel(ConsoleModel sysex) {
        initComponents();
        _list = sysex;
        _list.bind(jListScan); // 更新も自動
        _list._globalSelection = false;
        _list.addListDataListener(new ListDataListener() {
            @Override
            public void intervalAdded(ListDataEvent e) {
                jListScan.repaint();
            }

            @Override
            public void intervalRemoved(ListDataEvent e) {
                jListScan.repaint();
            }

            @Override
            public void contentsChanged(ListDataEvent e) {
                jListScan.repaint();
            }
        }
        );
        
        _file = new SysEXFile();
        _file.bind(jTextArea1);
        setPreferredSize(new Dimension(800, 600));
        
        jComboBoxPort.setModel(_listPort);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jListScan = new javax.swing.JList<>();
        jButtonLoadSysex = new javax.swing.JButton();
        jButtonSaveSysex = new javax.swing.JButton();
        jButtonDumpSysex = new javax.swing.JButton();
        jComboBoxPort = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButtonClearLog = new javax.swing.JButton();
        jButtonClearFile = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setViewportView(jListScan);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane1, gridBagConstraints);

        jButtonLoadSysex.setText("Load .sysex");
        jButtonLoadSysex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadSysexActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jButtonLoadSysex, gridBagConstraints);

        jButtonSaveSysex.setText("Save .sysex");
        jButtonSaveSysex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveSysexActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jButtonSaveSysex, gridBagConstraints);

        jButtonDumpSysex.setText("Dump To");
        jButtonDumpSysex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDumpSysexActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jButtonDumpSysex, gridBagConstraints);

        jComboBoxPort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        add(jComboBoxPort, gridBagConstraints);

        jButton5.setText("This Line To File");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        add(jButton5, gridBagConstraints);

        jToggleButton1.setText("Pause");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        add(jToggleButton1, gridBagConstraints);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jProgressBar1, gridBagConstraints);

        jButtonClearLog.setText("ClearLog");
        jButtonClearLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearLogActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jButtonClearLog, gridBagConstraints);

        jButtonClearFile.setText("ClearFile");
        jButtonClearFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearFileActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jButtonClearFile, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoadSysexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadSysexActionPerformed
        _file.clear(jTextArea1);
        MXFileOpenChooser chooser = new MXFileOpenChooser();
        chooser.addExtension(".txt", "TEXT");
        chooser.addExtension(".sysex", "SysEX");
        chooser.addExtension(".syx", "SysEX");
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            boolean success = false;
            if (file.getName().toLowerCase().endsWith(".txt")) { 
                success = _file.readText(file);
            }else {
                success = _file.readBinary(file);
            }
            _file.bind(jTextArea1);
            compactBeforeSend();
            if (success) {
                JOptionPane.showMessageDialog(this, "Done", "Done Read" + file , JOptionPane.OK_OPTION);
            }else {
                JOptionPane.showMessageDialog(this, "Fail", "Fail Read" + file , JOptionPane.OK_OPTION);
            }
        }
    }//GEN-LAST:event_jButtonLoadSysexActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        _list.switchPause(jToggleButton1.isSelected());
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int index = jListScan.getSelectedIndex();
        if (index >= 0) {
            ConsoleElement e = _list.getConsoleElement(index);
            switch (e.getType()) {
                case ConsoleElement.TYPE_DATA:
                    byte[] data = e.getData();
                    _file.add(data, jTextArea1);
                    break;
                case ConsoleElement.TYPE_MESSAGE:
                    byte[] data2 =  e.getMessage().getDataBytes();
                    _file.add(data2, jTextArea1);
                    break;
            }
            _file.bind(jTextArea1);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonSaveSysexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveSysexActionPerformed
        JFileChooser chooser = new JFileChooser();
        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            String extCheck = file.getName().toLowerCase();
            boolean isText = false;
            if (extCheck.endsWith(".txt")) {
                isText = true;
            }
            else  if (extCheck.endsWith(".sysex") || extCheck.endsWith("syx")) {
                isText = false;
            }
            else {
                int opt = JOptionPane.showConfirmDialog(this, "Save as Text?" , "SYSEX EXPORT", JOptionPane.YES_NO_OPTION);
                if (opt == JOptionPane.YES_OPTION) {
                    isText = true;
                }else {
                    isText = false;
                }
            }
            boolean success = false;
            try {
                if (isText) {
                    success = _file.writeText(file);
                }
                else {
                    success = _file.writeBinary(file);
                }
            }catch(IOException e) {
            }
            if (success) {
                JOptionPane.showMessageDialog(this, "Done", "Done Write " + file , JOptionPane.OK_OPTION);
            }else {
                JOptionPane.showMessageDialog(this, "Error", "Error", JOptionPane.OK_OPTION);
            }
        }  
    }//GEN-LAST:event_jButtonSaveSysexActionPerformed

    private void jButtonDumpSysexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDumpSysexActionPerformed
        // TODO add your handling code here:
        Integer port  = _listPort.readCombobox(jComboBoxPort);
        if (port != null) {
            _file.sendTo(port, new SysexProgress() {
                @Override
                public void progress(int pos, int total) {
                    jProgressBar1.setMaximum(total);
                    jProgressBar1.setValue(pos);
                }
            });
        }
    }//GEN-LAST:event_jButtonDumpSysexActionPerformed

    private void jButtonClearLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearLogActionPerformed
        // TODO add your handling code here:
        _list.clear();
        jListScan.repaint();
    }//GEN-LAST:event_jButtonClearLogActionPerformed

    private void jButtonClearFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearFileActionPerformed
        _file.clear(jTextArea1);
    }//GEN-LAST:event_jButtonClearFileActionPerformed

    public void compactBeforeSend() {
        ArrayList<byte[]> newList = new ArrayList();

        SysexSplitter splitter = null;

        for (byte[] data : _file._contents) {
            int ch = data[0] & 0xff;
            if (ch == 0xf0) {
                if (splitter != null) {
                    ArrayList<byte[]> ret = splitter.splitOrJoin(0);
                    newList.addAll(ret);
                }
                splitter = new SysexSplitter();
                splitter.append(data);
            }
            else if (ch == 0xf7) {
                if (splitter == null) {
                    JOptionPane.showMessageDialog(this, "No header for 0xf7 message");
                    return;
                }
                splitter.append(data);
            }
            else {
                JOptionPane.showMessageDialog(this, "Header not 0xf0 or 0xf7");
                return;
            }
        }
        if (splitter != null) {
            ArrayList<byte[]> ret = splitter.splitOrJoin(0);
            newList.addAll(ret);
        }
        if (splitter == null) {
            JOptionPane.showMessageDialog(this, "Any message not start with 0xf7");
            return;
        }
        
        ByteArrayOutputStream cache = new ByteArrayOutputStream();
        

        _file._contents = newList;
        _file.bind(jTextArea1);    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonClearFile;
    private javax.swing.JButton jButtonClearLog;
    private javax.swing.JButton jButtonDumpSysex;
    private javax.swing.JButton jButtonLoadSysex;
    private javax.swing.JButton jButtonSaveSysex;
    private javax.swing.JComboBox<String> jComboBoxPort;
    private javax.swing.JList<String> jListScan;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
