/*
 * Copyright 2023 Syntarou YOSHIDA.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jp.synthtarou.midimixer.libs.swing.attachment;

import java.awt.Dimension;
import jp.synthtarou.midimixer.libs.common.MXUtil;

/**
 *
 * @author Syntarou YOSHIDA
 */
public class TesterForCopyAndPaste extends javax.swing.JPanel {

    public static void main(String[] args) {
        MXUtil.showAsDialog(null, new TesterForCopyAndPaste(), "Test");
        System.exit(0);
    }

    /**
     * Creates new form ClipboardTestPanel
     */
    public TesterForCopyAndPaste() {
        initComponents();

        new MXAttachCopyAndPaste(jLabelTest);
        new MXAttachCopyAndPaste(jLabelTestR);
        new MXAttachCopyAndPaste(jLabelTestRW);

        new MXAttachCopyAndPaste(jTextAreaTest);
        new MXAttachCopyAndPaste(jTextAreaTestR);
        new MXAttachCopyAndPaste(jTextAreaTestRW);

        new MXAttachCopyAndPaste(jTextFieldTest);
        new MXAttachCopyAndPaste(jTextFieldTestR);
        new MXAttachCopyAndPaste(jTextFieldTestRW);
               
        setPreferredSize(new Dimension(500, 400));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelTest = new javax.swing.JLabel();
        jLabelTestR = new javax.swing.JLabel();
        jLabelTestRW = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaTest = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaTestR = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaTestRW = new javax.swing.JTextArea();
        jTextFieldTest = new javax.swing.JTextField();
        jTextFieldTestR = new javax.swing.JTextField();
        jTextFieldTestRW = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        jLabelTest.setText("jLabelTest");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jLabelTest, gridBagConstraints);

        jLabelTestR.setText("jLabelTestR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jLabelTestR, gridBagConstraints);

        jLabelTestRW.setText("jLabelTestRW");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jLabelTestRW, gridBagConstraints);

        jTextAreaTest.setColumns(20);
        jTextAreaTest.setRows(5);
        jScrollPane1.setViewportView(jTextAreaTest);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane1, gridBagConstraints);

        jTextAreaTestR.setColumns(20);
        jTextAreaTestR.setRows(5);
        jScrollPane2.setViewportView(jTextAreaTestR);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane2, gridBagConstraints);

        jTextAreaTestRW.setColumns(20);
        jTextAreaTestRW.setRows(5);
        jScrollPane3.setViewportView(jTextAreaTestRW);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane3, gridBagConstraints);

        jTextFieldTest.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jTextFieldTest, gridBagConstraints);

        jTextFieldTestR.setText("jTextField2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jTextFieldTestR, gridBagConstraints);

        jTextFieldTestRW.setText("jTextField3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jTextFieldTestRW, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTest;
    private javax.swing.JLabel jLabelTestR;
    private javax.swing.JLabel jLabelTestRW;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaTest;
    private javax.swing.JTextArea jTextAreaTestR;
    private javax.swing.JTextArea jTextAreaTestRW;
    private javax.swing.JTextField jTextFieldTest;
    private javax.swing.JTextField jTextFieldTestR;
    private javax.swing.JTextField jTextFieldTestRW;
    // End of variables declaration//GEN-END:variables
}
