/*
 * Copyright (C) 2023 Syntarou YOSHIDA.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jp.synthtarou.midimixer.mx36ccmapping;

import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import jp.synthtarou.midimixer.libs.swing.MXModalFrame;
import jp.synthtarou.midimixer.libs.accordion.MXAccordion;
/**
 *
 * @author Syntarou YOSHIDA
 */
public class MX36StatusListPanel extends javax.swing.JPanel {
    public static void main(String args[]) {
        MX36Process process = new MX36Process();
        MX36FolderList list = new MX36FolderList(process);
        
        MX36Folder folder = list.getPrimalFolder();
        folder.insertSorted(new MX36Status());
        folder.insertSorted(new MX36Status());
        folder.insertSorted(new MX36Status());
        folder.insertSorted(new MX36Status());
        folder = list.getAutoDetectedFolder();
        folder.insertSorted(new MX36Status());
        folder.insertSorted(new MX36Status());
        folder.insertSorted(new MX36Status());
        folder.insertSorted(new MX36Status());

        list.selectFirstAtm();

        MXModalFrame.showAsDialog(null, new MX36StatusListPanel(list), "test");
    }

    MX36FolderList _list;
    
    /**
     * Creates new form MXSampleMainPanel
     */
    public MX36StatusListPanel(MX36FolderList list) {
        initComponents();
        _list = list;
        
        jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);

        JPanel contents = new JPanel();
        contents.setLayout(new GridBagLayout());
        
        int y = 0;
        for (MX36Folder folder : list._listFolder) {
            MXAccordion accordion = folder._accordion;

            /*
            for (MX36Status status : folder._list) {
                folder.insertSorted(status);
            }*/
            GridBagConstraints lay1 = new GridBagConstraints(
                    0, y, 1, 1, 1, 0, 
                    GridBagConstraints.CENTER, GridBagConstraints.BOTH, 
                    new Insets(0, 0, 0, 0), 0, 0);
            contents.add(accordion, lay1);
            ++ y;
        }

        GridBagConstraints last = new GridBagConstraints(0, 10, 1, 1, 1, 1, GridBagConstraints.CENTER, GridBagConstraints.BOTH, new Insets(0, 0, 0, 0), 0, 0);
        contents.add(new JLabel(""), last);

        jScrollPane1.setViewportView(contents);
        
        setPreferredSize(new Dimension(800, 500));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
