/*
 * Copyright 2023 Syntarou YOSHIDA.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jp.synthtarou.midimixer.mx35cceditor;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import jp.synthtarou.midimixer.libs.navigator.INavigator;

/**
 *
 * @author Syntarou YOSHIDA
 */
public class AnotherTableEditPanel extends javax.swing.JPanel implements INavigator<String> {
    TableModelWithNavi _dataBase;
    int _dataRow;
    
    /*
     * Creates new form AnotherTableEditPanel
     */
    public AnotherTableEditPanel(TableModelWithNavi data, int row) {
        initComponents();
        _dataBase = data;
        _dataRow = row;
        
        reloadTable();
        setPreferredSize(new Dimension(400, 150));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(1, 2));
    }// </editor-fold>//GEN-END:initComponents


    public void reloadTable() {
        removeAll();
        setLayout(new GridBagLayout());
        GridBagConstraints con;
        
        for (int y = 0; y < _dataBase.getColumnCount(); ++ y) {
            String name = _dataBase.getColumnName(y);
            String text = _dataBase.getValueAsText(_dataRow, y);

            JLabel label = new JLabel(name);
            JTextField field = new JTextField(text);
            
            field.setEditable(false);
            field.setBackground(Color.white);
            
            label.addMouseListener(new RowEditAction(y));
            field.addMouseListener(new RowEditAction(y));
            
            con = new GridBagConstraints();
            con.gridx = 0;
            con.gridy = y;
            con.weightx = 0;
            con.fill = GridBagConstraints.NONE;
            add(label, con);
            con = new GridBagConstraints();
            con.gridx = 1;
            con.gridy = y;
            con.weightx = 1;
            con.fill = GridBagConstraints.HORIZONTAL;
            add(field, con);
        }
        JLabel fill = new JLabel(" ");
        con = new GridBagConstraints();
        con.gridx = 0;
        con.gridy = _dataBase.getColumnCount();
        con.weighty = 1;
        con.fill = GridBagConstraints.VERTICAL;
        add(fill, con);
        updateUI();

        //MXMain.getMain().getCCEditorProcess().getReceiverView().revalidate();
    }

    @Override
    public JPanel getNavigatorPanel() {
        return this;
    }

    @Override
    public int getNavigatorType() {
        return INavigator.TYPE_EDITOR;
    }

    @Override
    public boolean isNavigatorRemovable() {
        return false;
    }

    @Override
    public boolean validateWithNavigator(String result) {
        return true;
   }

    @Override
    public int getReturnStatus() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public String getReturnValue() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    public class RowEditAction extends MouseAdapter {
        int _dataColumn;
        public RowEditAction(int column) {
            _dataColumn = column;
        }

        @Override
        public void mousePressed(MouseEvent e) {
            if (_dataBase.startCellEdit(AnotherTableEditPanel.this, _dataRow, _dataColumn)) {
                reloadTable();
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
