/*
 * Copyright 2023 Syntarou YOSHIDA.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jp.synthtarou.midimixer.mx10input;

import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import jp.synthtarou.libs.log.MXFileLogger;
import jp.synthtarou.libs.namedobject.MXNamedObjectList;
import jp.synthtarou.midimixer.libs.midi.port.MXMIDIIn;
import jp.synthtarou.midimixer.libs.midi.port.MXMIDIInManager;
import jp.synthtarou.midimixer.mx13patch.MX13Process;

/**
 *
 * @author Syntarou YOSHIDA
 */
public class MX10MidiInListPanel extends javax.swing.JPanel {
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableDevice;
    private MX10Process _process;
    
    public MX10MidiInListPanel(MX10Process process) {
        initComponents();
        _process = process;

        MXMIDIInManager manager = MXMIDIInManager.getManager();

        jTableDevice = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane(jTableDevice);
        
        jTableDevice.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTableDevice.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int row = jTableDevice.getSelectedRow();
                if (row >= 0) {
                    MXMIDIInManager manager = MXMIDIInManager.getManager();
                    MXMIDIIn input = manager.listAllInput().valueOfIndex(row);
                    _process.showMIDIInDetail(input);
                }
            }
        });
        add(jScrollPane4);
        
        refreshList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents

    public void refreshList() {
        if (!SwingUtilities.isEventDispatchThread()) {
            SwingUtilities.invokeLater(this::refreshList);
            return;
        }
        MXMIDIInManager manager = MXMIDIInManager.getManager();
        manager.reloadDeviceList();

        jTableDevice.setModel(createDeviceModel());
        jTableDevice.getColumnModel().getColumn(2).setWidth(500);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public TableModel createDeviceModel() {
        MXNamedObjectList<MXMIDIIn> allInput = MXMIDIInManager.getManager().listAllInput();
        MXMIDIInManager manager = MXMIDIInManager.getManager();
        DefaultTableModel tableModel = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tableModel.addColumn("Port");
        tableModel.addColumn("Assign");
        tableModel.addColumn("Filter");
        tableModel.addColumn("Open");

        for (MXMIDIIn input : allInput.valueList()) {
            String prefix = "";
            tableModel.addRow(new Object[] { 
                prefix + input.getName(),
                input.getPortAssignedAsText(),
                MX13Process.getFilterInfo(input),
                input.isOpen() ? "o" : "-"
            });
        }
        
        return tableModel;
    }
    
    public void updateDeviceTable() {
        DefaultTableModel model = (DefaultTableModel)jTableDevice.getModel();
        TableModel newModel = createDeviceModel();
        for (int i = 0; i < model.getRowCount(); ++ i) {
            String name = (String)model.getValueAt(i, 0);
            String value = (String)model.getValueAt(i, 1);
            String opened = (String)model.getValueAt(i, 2);
            
            String newName = (String)newModel.getValueAt(i, 0);
            String newValue = (String)newModel.getValueAt(i, 1);
            String newSkip = (String) newModel.getValueAt(i, 2);
            String newOpen = (String)newModel.getValueAt(i, 3);
            
            if (name.equals(newName) == false) {
                MXFileLogger.getLogger(MX10MidiInListPanel.class).warning("any troubole?");
                break;
            }
            
            model.setValueAt(newValue, i, 1);
            model.setValueAt(newSkip, i, 2);
            model.setValueAt(newOpen, i, 3);
        }
    }
}
