/*
 * Copyright (C) 2024 yaman
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jp.synthtarou.midimixer.mx00playlist;

import java.awt.Dimension;
import javax.swing.JFrame;
import jp.synthtarou.midimixer.libs.common.MXUtil;
import jp.synthtarou.midimixer.libs.namedvalue.MNamedValueList;
import jp.synthtarou.midimixer.libs.navigator.MXPopupForList;

/**
 *
 * @author yaman
 */
public class MXPianoRollSettings extends javax.swing.JPanel {
    MXPianoRoll _roll;
    MNamedValueList<Integer> listColor = new MNamedValueList();
    MNamedValueList<Integer> listMagin = new MNamedValueList();
    MNamedValueList<Integer> listSpan = new MNamedValueList();
    MNamedValueList<Integer> listTiming = new MNamedValueList();


    /**
     * Creates new form PianoRollSettings
     */
    public MXPianoRollSettings(MXPianoRoll roll) {
        initComponents();
        _roll = roll;
        MXUtil.centerWindow(this);

        jTextFieldColor.setEditable(false);
        jTextFieldMargin.setEditable(false);
        jTextFieldSpan.setEditable(false);

        listColor.addNameAndValue("Color", -1);
        for (int ch = 0; ch < 16; ++ ch) {
            listColor.addNameAndValue("Ch " +(ch+1), ch);
        }
        for (int margin = 0; margin <= 1000; margin += 100) {
            listMagin.addNameAndValue(margin + " msec", margin);
        }
        for (int span = 2000; span <= 10000; span += 1000) {
            listSpan.addNameAndValue((span / 1000) + " sec", span);
        }
        listTiming.addNameAndValue("Off", 0);
        listTiming.addNameAndValue("On", 1);
        
        jTextFieldColor.setText(listColor.nameOfValue(_roll.getFocuChannel()));
        MXPopupForList<Integer> popupForColor = new MXPopupForList<Integer>(jTextFieldColor, listColor) {
            @Override
            public void approvedIndex(int selectedIndex) {
                int value = listColor.valueOfIndex(selectedIndex);
                _roll.setFocusChannel(value);
                jTextFieldColor.setText(listColor.nameOfValue(_roll.getFocuChannel()));
            }
        };
        jTextFieldMargin.setText(listMagin.nameOfValue((int)_roll.getSoundMargin()));
        MXPopupForList<Integer> popupForMargin = new MXPopupForList<Integer>(jTextFieldMargin, listMagin) {
            @Override
            public void approvedIndex(int selectedIndex) {
                int value = listMagin.valueOfIndex(selectedIndex);
                _roll.setSoundMargin(value);
                jTextFieldMargin.setText(listMagin.nameOfValue((int)_roll.getSoundMargin()));
            }
        };
        jTextFieldSpan.setText(listSpan.nameOfValue((int)_roll.getSoundSpan()));
        MXPopupForList<Integer> popupForSpan = new MXPopupForList<Integer>(jTextFieldSpan, listSpan) {
            @Override
            public void approvedIndex(int selectedIndex) {
                int value = listSpan.valueOfIndex(selectedIndex);
                _roll.setSoundSpan(value);
                jTextFieldSpan.setText(listSpan.nameOfValue((int)_roll.getSoundSpan()));
            }
        };

        jTextFieldShowTiming.setText(listTiming.nameOfValue(_roll._showTempo ? Integer.valueOf(1) : Integer.valueOf(0)));
        MXPopupForList<Integer> popupForTiming = new MXPopupForList<Integer>(jTextFieldShowTiming, listTiming) {
            @Override
            public void approvedIndex(int selectedIndex) {
                int value = listTiming.valueOfIndex(selectedIndex);
                _roll._showTempo = value > 0;
                jTextFieldShowTiming.setText(listTiming.nameOfValue(_roll._showTempo ? Integer.valueOf(1) : Integer.valueOf(0)));
            }
        };
        this.setSize(new Dimension(350, 150));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jTextFieldColor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSpan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMargin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldShowTiming = new javax.swing.JTextField();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Color");
        add(jLabel1);

        jTextFieldColor.setEditable(false);
        add(jTextFieldColor);

        jLabel3.setText("Range");
        add(jLabel3);

        jTextFieldSpan.setEditable(false);
        add(jTextFieldSpan);

        jLabel2.setText("Margin");
        add(jLabel2);

        jTextFieldMargin.setEditable(false);
        add(jTextFieldMargin);

        jLabel4.setText("Timing");
        add(jLabel4);

        jTextFieldShowTiming.setEditable(false);
        add(jTextFieldShowTiming);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldColor;
    private javax.swing.JTextField jTextFieldMargin;
    private javax.swing.JTextField jTextFieldShowTiming;
    private javax.swing.JTextField jTextFieldSpan;
    // End of variables declaration//GEN-END:variables
}
