/*
 * Copyright (C) 2024 Syntarou YOSHIDA
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jp.synthtarou.mixtone.main.view;

import java.io.File;
import javax.swing.JFileChooser;
import jp.synthtarou.mixtone.listmodel.ListModelINSTBagTable;
import jp.synthtarou.mixtone.listmodel.ListModelINSTList;
import jp.synthtarou.mixtone.listmodel.ListModelINSTSHDRProperty;
import jp.synthtarou.mixtone.listmodel.ListModelPHDRBagTable;
import jp.synthtarou.mixtone.listmodel.ListModelPHDRList;
import jp.synthtarou.mixtone.listmodel.TheConsole;
import jp.synthtarou.mixtone.main.XTSynthesizer;
import jp.synthtarou.mixtone.synth.oscilator.XTOscilator;

/**
 *
 * @author Syntarou YOSHIDA
 */
public class XTSoundFontView extends javax.swing.JPanel {

    /**
     * Creates new form XTMixerView
     */
    public XTSoundFontView(XTSynthesizer synth) {
        initComponents();
        _synth = synth;
        _console = new TheConsole();
        _console.attach(jListDebug);
        jTextFieldFileName.setEditable(false);
    }
    
    XTSynthesizer _synth;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTextFieldFileName = new javax.swing.JTextField();
        jButtonBrowse = new javax.swing.JButton();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListDebug = new javax.swing.JList<>();
        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListPHDRList = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListPHDRBagProperty = new javax.swing.JList<>();
        jSplitPane4 = new javax.swing.JSplitPane();
        jPanelInstrument = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListInstrumentList = new javax.swing.JList<>();
        jPanelZone = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListInstBagProperty = new javax.swing.JList<>();
        jButton60 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListSHDRProperty = new javax.swing.JList<>();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(jTextFieldFileName, gridBagConstraints);

        jButtonBrowse.setText("Browse");
        jButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jButtonBrowse, gridBagConstraints);

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Logging"));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setViewportView(jListDebug);

        jPanel5.add(jScrollPane1);

        jSplitPane2.setLeftComponent(jPanel5);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane3.setDividerLocation(300);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Preset"));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jListPHDRList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListPHDRListValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(jListPHDRList);

        jPanel1.add(jScrollPane5);

        jSplitPane3.setLeftComponent(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("PresetBag ListEntries"));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jListPHDRBagProperty.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListPHDRBagPropertyValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(jListPHDRBagProperty);

        jPanel2.add(jScrollPane6);

        jSplitPane3.setRightComponent(jPanel2);

        jSplitPane1.setLeftComponent(jSplitPane3);

        jSplitPane4.setDividerLocation(300);

        jPanelInstrument.setBorder(javax.swing.BorderFactory.createTitledBorder("Instrument"));
        jPanelInstrument.setLayout(new javax.swing.BoxLayout(jPanelInstrument, javax.swing.BoxLayout.LINE_AXIS));

        jListInstrumentList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListInstrumentListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListInstrumentList);

        jPanelInstrument.add(jScrollPane2);

        jSplitPane4.setLeftComponent(jPanelInstrument);

        jPanelZone.setBorder(javax.swing.BorderFactory.createTitledBorder("InstrumentBag ListEntry"));
        jPanelZone.setLayout(new java.awt.GridBagLayout());

        jListInstBagProperty.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListInstBagPropertyValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(jListInstBagProperty);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelZone.add(jScrollPane4, gridBagConstraints);

        jButton60.setText("Play 60");
        jButton60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton60ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        jPanelZone.add(jButton60, gridBagConstraints);

        jScrollPane3.setViewportView(jListSHDRProperty);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanelZone.add(jScrollPane3, gridBagConstraints);

        jButton61.setText("Play 61");
        jButton61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton61ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        jPanelZone.add(jButton61, gridBagConstraints);

        jButton62.setText("Play 62");
        jButton62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton62ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        jPanelZone.add(jButton62, gridBagConstraints);

        jButton63.setText("Play 63");
        jButton63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton63ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanelZone.add(jButton63, gridBagConstraints);

        jButton64.setText("Play 64");
        jButton64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton64ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        jPanelZone.add(jButton64, gridBagConstraints);

        jButton69.setText("Play 69");
        jButton69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton69ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        jPanelZone.add(jButton69, gridBagConstraints);

        jButton70.setText("Play 70");
        jButton70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton70ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        jPanelZone.add(jButton70, gridBagConstraints);

        jSplitPane4.setRightComponent(jPanelZone);

        jSplitPane1.setRightComponent(jSplitPane4);

        jSplitPane2.setRightComponent(jSplitPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jSplitPane2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser("c:\\midi");
        chooser.showOpenDialog(this);
        File f = chooser.getSelectedFile();
        if (f != null) {
            jTextFieldFileName.setText("" + f);
            startOpen(f);
        }
    }//GEN-LAST:event_jButtonBrowseActionPerformed

    private void jListPHDRListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListPHDRListValueChanged
        int index = jListPHDRList.getSelectedIndex();
        if (index >= 0) {
            try {
                ListModelPHDRBagTable model = _listModelPHDRList.getAsPHDRBagTable(index);
                if (model != null) {
                    _listModelPHDRBagList = model;
                    jListPHDRBagProperty.setModel(model);
                }
            }catch(IndexOutOfBoundsException ex) {
                ex.printStackTrace();
            }catch(Throwable ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jListPHDRListValueChanged

    private void jListPHDRBagPropertyValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListPHDRBagPropertyValueChanged
        int index = jListPHDRBagProperty.getSelectedIndex();
        if (index >= 0) {
            try {
                int instrument = _listModelPHDRBagList.getInstrumentOf(index);
                ListModelINSTBagTable model = _listModelINSTList.getAsINSTBagTable(instrument);
                if (model != null) {
                    _listModelINSTBagList = model;
                    jListInstBagProperty.setModel(model);
                }
            }catch(IndexOutOfBoundsException ex) {
                ex.printStackTrace();
            }catch(Throwable ex) {
                ex.printStackTrace();
            }
        }

    }//GEN-LAST:event_jListPHDRBagPropertyValueChanged

    private void jListInstrumentListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListInstrumentListValueChanged
        int index = jListInstrumentList.getSelectedIndex();
        if (index >= 0) {
            try {
                ListModelINSTBagTable model = _listModelINSTList.getAsINSTBagTable(index);
                if (model != null) {
                    _listModelINSTBagList = model;
                    jListInstBagProperty.setModel(model);
                }
            }catch(IndexOutOfBoundsException ex) {
                ex.printStackTrace();
            }catch(Throwable ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jListInstrumentListValueChanged

    private void jListInstBagPropertyValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListInstBagPropertyValueChanged
        int index = jListInstBagProperty.getSelectedIndex();
        if (index >= 0) {
            try {
                int sampleId = _listModelINSTBagList.getSampleIdOf(index);
                int overridingRootKey = _listModelINSTBagList.getOverridingRootKeyOf(index);
                boolean loop = _listModelINSTBagList.getLoopOf(index);
                _listModelSHDRProperty = new ListModelINSTSHDRProperty(_synth._sfz, sampleId, loop, overridingRootKey);
                jListSHDRProperty.setModel(_listModelSHDRProperty);
            }catch(IndexOutOfBoundsException ex) {
                ex.printStackTrace();
            }catch(Throwable ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jListInstBagPropertyValueChanged

    private void jButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton60ActionPerformed
        playOneShot(60);
    }//GEN-LAST:event_jButton60ActionPerformed

    private void jButton61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton61ActionPerformed
        playOneShot(61);
    }//GEN-LAST:event_jButton61ActionPerformed

    private void jButton62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton62ActionPerformed
        playOneShot(62);
    }//GEN-LAST:event_jButton62ActionPerformed

    private void jButton63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton63ActionPerformed
        playOneShot(63);
    }//GEN-LAST:event_jButton63ActionPerformed

    private void jButton64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton64ActionPerformed
        playOneShot(64);
    }//GEN-LAST:event_jButton64ActionPerformed

    private void jButton69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton69ActionPerformed
        playOneShot(69);
    }//GEN-LAST:event_jButton69ActionPerformed

    private void jButton70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton70ActionPerformed
        playOneShot(70);
    }//GEN-LAST:event_jButton70ActionPerformed

    TheConsole _console;            

    public void startOpen(File f) {
        StringBuilder text = new StringBuilder();
        try {
            _synth.openSoundfont(f);
            _synth.dump(_console);
            _synth.reset();
            listInstrument();
            listPreset();
        }catch(Throwable ex) {
            text.append("exception " + ex.toString() + "\n");
            ex.printStackTrace();
        }
    }
    
    ListModelINSTList _listModelINSTList;
    ListModelINSTBagTable _listModelINSTBagList;
    ListModelPHDRList _listModelPHDRList;
    ListModelPHDRBagTable _listModelPHDRBagList;
    ListModelINSTSHDRProperty _listModelSHDRProperty;
    
    public void listInstrument() {
        _listModelINSTList = new ListModelINSTList(_synth._sfz);
        jListInstrumentList.setModel(_listModelINSTList);
    }
    
    public void listPreset() {
        _listModelPHDRList = new ListModelPHDRList(_synth._sfz);
        jListPHDRList.setModel(_listModelPHDRList);
    }
    
    public void playOneShot(int note) {
        if (_listModelSHDRProperty != null) {
            XTOscilator osc = _listModelSHDRProperty.newOscilator(note);
            _synth.prepareAudioStream().addToQueue(osc);
            new Thread(() -> {
                try {
                    Thread.sleep(1000);
                }catch(Throwable ex) {
                    
                }
                osc.noteOff();
            }).start();
        }    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButtonBrowse;
    private javax.swing.JList<String> jListDebug;
    private javax.swing.JList<String> jListInstBagProperty;
    private javax.swing.JList<String> jListInstrumentList;
    private javax.swing.JList<String> jListPHDRBagProperty;
    private javax.swing.JList<String> jListPHDRList;
    private javax.swing.JList<String> jListSHDRProperty;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelInstrument;
    private javax.swing.JPanel jPanelZone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JTextField jTextFieldFileName;
    // End of variables declaration//GEN-END:variables
}
